"""empty message

Revision ID: 5554861b1be8
Revises: 4b31293792b5
Create Date: 2022-11-23 23:07:01.994088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5554861b1be8'
down_revision = '4b31293792b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make', sa.String(length=150), nullable=False),
    sa.Column('model', sa.String(length=200), nullable=True),
    sa.Column('year', sa.String(length=5), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
